name: hoor_manager
description: "تطبيق إدارة مبيعات متجر Hoor"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Firebase
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  firebase_storage: ^13.0.5
  
  # Google Sign In
  google_sign_in: ^6.2.2
  
  # State Management
  provider: ^6.1.2
  
  # UI
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  flutter_spinkit: ^5.2.1
  
  # Utils
  intl: ^0.20.2
  uuid: ^4.5.1
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  
  # PDF & Printing
  pdf: ^3.11.2
  printing: ^5.14.2
  
  # Storage
  shared_preferences: ^2.3.5
  
  # Logging
  logger: ^2.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # --- Development & Performance ---
  flutter_lints: ^6.0.0
  device_preview: ^1.2.0
  leak_tracker: ^11.0.2

flutter:
  uses-material-design: true